# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: DCFemTech
email: dcfemtech@gmail.com
image: assets/cover.jpg
description: > # this means to ignore newlines until "baseurl:"
  DCFemTech is a coalition of women leaders aimed at amplifying women in tech organizations, sharing resources, and bringing leaders together to close the gender gap. Bimonthly meetings are inclusive and open to any women in tech leaders. Members are affiliated with organizations with women attendance that is 50% or higher; who have a focus on technology; and have a primary focus in the mission statement about gender or women.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://dcfemtech.github.io" # the base hostname & protocol for your site
twitter_username: dcfemtech
github_username:  dcfemtech

# Build settings
markdown: kramdown

# Collections
collections:
  members:
    output: true
    permalink: /:path
  events:
    output: true
    permalink: /:path

# Redirects
gems:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from
